name = "Newb Reimagined"
version = [0, 15, 65]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§7Shader that have a vanilla minecraft feel but improved
%v
§3https://github.com/alyow/newb-reimagined/
''' # %w = patch warning, %v = version
authors = ["al_yoww", "devendrn"]
url = "https://github.com/alyow/newb-reimagined/"
uuid = "b1a6a0f0-8279-4138-b09c-99391d4ac8ed" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Actor"]

[info] 
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited and do not use any assets from this shader without permission!
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "COMP_VANILLA"
materials = ["RenderChunk", "Clouds", "LegacyCubemap", "Sky", "EndSky"]
description = '''
§bNewb Reimagined§r\n Soft Clouds\n Aurora §bLight Blue §aGreen§r\n Wavy Water
'''

[[subpack]]
define = "COMP_SOFT"
materials = ["RenderChunk", "Clouds", "LegacyCubemap", "Sky", "EndSky"]
description = '''
§bNewb Reimagined§r\n Soft Clouds\n Aurora §bLight Blue §aGreen§r\n Wavy Water
'''

[[subpack]]
define = "COMP_DC"
materials = ["RenderChunk", "Clouds", "LegacyCubemap", "Sky", "EndSky"]
description = '''
§bNewb Reimagined§r\n Soft Clouds\n Aurora §bLight Blue §aGreen§r\n Wavy Water
'''

[[subpack]]
define = "COMP_GR"
materials = ["RenderChunk", "Clouds", "LegacyCubemap", "Sky", "EndSky"]
description = '''
§bNewb Reimagined§r\n Soft Clouds\n Aurora §bLight Blue §aGreen§r\n Wavy Water
'''

[[subpack]]
define = "COMP_AURORA"
materials = ["RenderChunk", "Clouds", "LegacyCubemap", "Sky", "EndSky"]
description = '''
§bNewb Reimagined§r\n Soft Clouds\n Aurora §bLight Blue §aGreen§r\n Wavy Water
'''

[[subpack]]
define = "COMP_DEF"
materials = ["RenderChunk", "Clouds", "LegacyCubemap", "Sky", "EndSky"]
description = '''
§bNewb Reimagined§r\n Soft Clouds\n Aurora §bLight Blue §aGreen§r\n Wavy Water
'''