name = "Newb Reimagined"
version = [0, 16, 0]
min_supported_mc_version = [1, 21, 20]
description = '''
§7A fantasy-themed shader that keeps the vanilla Minecraft feel.
%v
§c%w
''' # %w = patch warning, %v = version
authors = ["alyowv", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "96f0bc06-7515-4fe0-83de-c61657271875" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]
text = " Recommended Settings:\n§7 Set brightness to 10 - 50§r\n\n Info!\n §7Shader are not officially supported on vanilla MCBE!\n You need a shader loader or a modified client\n for Minecraft Bedrock. Some devices will also experience\n cloud-cutting bugs.§r" 

[info] 
copyright = '''
Copyright © 2025 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "LOW"
materials = ["RenderChunk"]
description = '''
§aLow
§7Disable plants wave, glow leak and many more!
'''

[[subpack]]
define = "PERFORMANCE"
materials = ["RenderChunk"]
description = '''
§2Performance
§7Disable glow leak, lava noise and reflections
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No Plants Wave
§7Just disable plants wave
'''

[[subpack]]
define = "VANILLA_CLOUDS"
materials = ["Clouds"]
description = '''
Vanilla Clouds
§7Vanilla clouds without aurora
'''

[[subpack]]
define = "DOUBLE_CLOUDS"
materials = ["Clouds"]
description = '''
Double Cloud Layers
§7Multilayer clouds without aurora
'''

[[subpack]]
define = "GALAXY"
materials = ["RenderChunk", "Sky"]
description = '''
Galaxy Star
§7Galaxy star with shooting stars
'''

[[subpack]]
define = "AURORA2"
materials = ["RenderChunk", "Clouds"]
description = '''
Aurora
§7Aurora §blight blue §agreen§r
'''

[[subpack]]
define = "AURORA1"
materials = ["RenderChunk", "Clouds"]
description = '''
Aurora
§7Aurora §blight blue §upurple§r
'''

[[subpack]]
define = "FAKE_DEPTH"
materials = ["RenderChunk"]
description = '''
Fake Depth
§7Enable fake depth and block reflection
'''

[[subpack]]
define = "DEF"
materials = []
description = '''
Default
§7Rounded clouds without aurora
'''
