name = "Newb Reimagined"
version = [0, 15, 6]
min_supported_mc_version = [1, 20, 80]
url = "https://github.com/alyow/newb-reimagined/"
authors = ["al_yoww"]
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Actor"]

[description]
# %w = patch warning, %v = version
long = '''
§c%w
§7Shader that have a vanilla minecraft feel but improved
%v
§3https://github.com/alyow/newb-reimagined/
'''
short = "A variant of Newb Shader for RenderDragon"

[uuid] # Use https://www.uuidgenerator.net/version4
header = "356f6017-5c98-41b1-bf6c-57e81a43144a"
module = "7a9b03b2-6d6e-4781-ab05-27d726f83a23"

[info]
# %a = authors
copyright = '''
Copyright (c) %a

**Important Note:** Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited and do not use any assets from this shader without permission!
'''
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default
[[subpack]]
define = "DEF_VANILLA"
materials = ["RenderChunk", "Clouds"]
description = '''
§bNewb Reimagined§r\n Vanilla Clouds\n No Aurora\n Wavy Water
'''

[[subpack]]
define = "DEF_SOFT"
materials = ["RenderChunk", "Clouds"]
description = '''
§bNewb Reimagined§r\n Soft Clouds\n Aurora §bLight Blue §aGreen§r\n Wavy Water
'''

[[subpack]]
define = "DEF_NW"
materials = ["RenderChunk", "Clouds"]
description = '''
§bNewb Reimagined§r\n Rounded Clouds, Aurora §bLight Blue §aGreen§r\n No Wave\n Reimagined Water
'''

[[subpack]]
define = "DEF_DC"
materials = ["RenderChunk", "Clouds"]
description = '''
§bNewb Reimagined§r\n Double Cloud Layers\n Aurora §bLight Blue §aGreen§r\n Reimagined Water
'''

[[subpack]]
define = "DEF_GR"
materials = ["RenderChunk", "Clouds"]
description = '''
§bNewb Reimagined§r\n Rounded Clouds, Aurora §bLight Blue §aGreen§r\n Ground Reflection, Rainbow\n Wavy Water
'''

[[subpack]]
define = "DEF_AURORA"
materials = ["RenderChunk", "Clouds"]
description = '''
§bNewb Reimagined§r\n Rounded Clouds, Aurora §bLight Blue §aGreen§r\n Blinking Torch\n Reimagined Water
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
§bNewb Reimagined Default§r\n Rounded Clouds\n No Aurora\n Reimagined Water
'''
