name = "Newb Reimagined"
version = [0, 15, 75]
min_supported_mc_version = [1, 21, 20]
description = '''
§7A shader with a fantasy theme without losing the vanilla minecraft feel
%v
§c%w
''' # %w = patch warning, %v = version
authors = ["alyowv", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "95f774cf-4afa-73e7-a21a-72146307b1d2" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]
text = " Recommended:\n§7 Set brightness to 10 - 30\n Put this shader on top if not using an animation pack" 

[info] 
copyright = '''
Copyright © 2024 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "LOW"
materials = ["RenderChunk"]
description = '''
§aLow
§7Disable plants wave, glow leak, godrays, lava noise, and reflections
'''

[[subpack]]
define = "MEDIUM"
materials = ["RenderChunk"]
description = '''
§2Medium
§7Disable glow leak, lava noise and reflections
'''

[[subpack]]
define = "VANILLA_CLOUDS"
materials = ["Clouds"]
description = '''
Vanilla Clouds
§7Vanilla clouds without aurora
'''

[[subpack]]
define = "SOFT_CLOUDS"
materials = ["RenderChunk", "Clouds"]
description = '''
Soft Clouds
§7Soft clouds but cirrus clouds style, no aurora
'''

[[subpack]]
define = "REALISTIC_CLOUDS_A"
materials = ["Clouds"]
description = '''
Realistic Clouds
§7Volumetric clouds with aurora §blight blue §upurple§r
'''

[[subpack]]
define = "REALISTIC_CLOUDS"
materials = ["Clouds"]
description = '''
Realistic Clouds
§7Volumetric clouds without aurora
'''

[[subpack]]
define = "DOUBLE_CLOUDS"
materials = ["Clouds"]
description = '''
Double Cloud Layers
§7Multilayer clouds without aurora
'''

[[subpack]]
define = "ALWAYS_REFL"
materials = ["RenderChunk", "Sky", "Clouds"]
description = '''
Always Reflection
§7Ground reflection with aurora reflection
'''

[[subpack]]
define = "GALAXY"
materials = ["RenderChunk", "Sky"]
description = '''
Galaxy Star
§7Galaxy star without aurora
'''

[[subpack]]
define = "AURORA2"
materials = ["RenderChunk", "Clouds"]
description = '''
Aurora
§7Aurora §blight blue §agreen§r
'''

[[subpack]]
define = "AURORA1"
materials = ["RenderChunk", "Clouds"]
description = '''
Aurora
§7Aurora §blight blue §upurple§r
'''

[[subpack]]
define = "COMP"
materials = []
description = '''
Default
§7Rounded clouds without aurora
'''
